#!/bin/bash

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ARCH=$1
PLAT=$2
LCBVER=${LCBVER:-2.5.3}

echo "Installing libcouchbase $ARCH"
./lsetup_lcb $LCBVER $ARCH $PLAT

echo "Installing Node.js $ARCH"
./lsetup_njs njs 0.10.42 $ARCH $PLAT
./lsetup_njs njs 0.12.10 $ARCH $PLAT
./lsetup_njs njs 4.3.0 $ARCH $PLAT
./lsetup_njs njs 5.6.0 $ARCH $PLAT

echo "Installing PHP $ARCH"
./lsetup_php 5.4.45 $ARCH $PLAT
./lsetup_php 5.5.31 $ARCH $PLAT
./lsetup_php 5.6.17 $ARCH $PLAT
./lsetup_php 7.0.5 $ARCH $PLAT
