#!/bin/bash

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ARCH=$1
PLAT=$2
LCBVER=${LCBVER:-2.6.3}

echo "Installing libcouchbase $ARCH"
./lsetup_lcb $LCBVER $ARCH $PLAT

echo "Installing Node.js $ARCH"
./lsetup_njs njs 0.10.44 $ARCH $PLAT
./lsetup_njs njs 0.12.13 $ARCH $PLAT
./lsetup_njs njs 4.4.3 $ARCH $PLAT
./lsetup_njs njs 5.11.0 $ARCH $PLAT
./lsetup_njs njs 6.0.0 $ARCH $PLAT

echo "Installing PHP $ARCH"
./lsetup_php 5.4.45 $ARCH $PLAT
./lsetup_php 5.5.38 $ARCH $PLAT
./lsetup_php 5.6.26 $ARCH $PLAT
./lsetup_php 7.0.11 $ARCH $PLAT
