#!/usr/bin/env bash
set -xe

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. common/env

echo "Preparing"
mkdir -p tmp
mkdir -p src
mkdir -p lcb-files
mkdir -p lcb-files/build
mkdir -p lcb-files/src
mkdir -p php-files
mkdir -p php-files/build
mkdir -p php-files/deps
mkdir -p php-files/src
mkdir -p njs-files

if [ "$MACHINE_ARCH" == "x64" ]; then
  ./lsetup_all x64 $PLAT
  ./lsetup_all x86 $PLAT
fi
if [ "$MACHINE_ARCH" == "x86" ]; then
  ./lsetup_all x86 $PLAT
fi


echo "Cleaning Up"
rm -rf tmp
