#!/usr/bin/env bash
set -xe

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ARCH=$1
PLAT=$2
LCBVER=${LCBVER:-2.8.3}

echo "Installing libcouchbase $ARCH"
./lsetup_lcb $LCBVER $ARCH $PLAT

 echo "Installing Node.js $ARCH"
 ./lsetup_njs njs 0.10.48 $ARCH $PLAT
 ./lsetup_njs njs 0.12.17 $ARCH $PLAT
 ./lsetup_njs njs 4.6.1 $ARCH $PLAT
 ./lsetup_njs njs 5.12.0 $ARCH $PLAT
 ./lsetup_njs njs 6.9.4 $ARCH $PLAT
 ./lsetup_njs njs 7.4.0 $ARCH $PLAT
 ./lsetup_njs njs 8.9.0 $ARCH $PLAT

echo "Installing PHP $ARCH"
./lsetup_php 5.6.32 $ARCH $PLAT
./lsetup_php 7.0.26 $ARCH $PLAT
./lsetup_php 7.1.12 $ARCH $PLAT
