#!/bin/bash -xe

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PHPVER=$1
PHPTS=$2
ARCH=$3

echo "Building PHP $1 $2 $3"

PHPTAG=$PHPVER-$PHPTS-$ARCH

. common/env $ARCH

cd php-files/src/$PHPTAG

ZTSARG=''
if [ "$PHPTS" = 'zts' ]; then
  ZTSARG='--enable-maintainer-zts'
fi
case "$PHPVER" in
  5.6*)
    patch < $MYDIR/php/patches/php-5.6-fix-config-nice-generator.patch
  ;;
esac

./configure --disable-all --enable-phar=shared --enable-json --enable-cli --prefix=$MYDIR/php-files/build/$PHPTAG $ZTSARG CFLAGS="-ggdb3 $CFLAGS" && make && make install

