#!/usr/bin/env bash

set -xe

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PHPVER=$1
PHPTS=$2
ARCH=$3
IGBINARY_VER=$4

echo "Building PHP $1 $2 $3"

PHPTAG=$PHPVER-$PHPTS-$ARCH

. common/env $ARCH

cd php-files/src/$PHPTAG

ZTSARG=''
if [ "$PHPTS" = 'zts' ]; then
  ZTSARG='--enable-maintainer-zts'
fi
case "$PHPVER" in
  5.6*)
    patch < $MYDIR/php/patches/php-5.6-fix-config-nice-generator.patch
  ;;
esac

PREFIX=$MYDIR/php-files/build/$PHPTAG
./configure --disable-all --enable-phar=shared --enable-json --enable-cli --with-zlib --prefix=$PREFIX $ZTSARG CFLAGS="-ggdb3 $CFLAGS" && make -j8 && make install
(
  cd igbinary-${IGBINARY_VER}
  $PREFIX/bin/phpize
  ./configure --with-php-config=$PREFIX/bin/php-config $($PREFIX/bin/php-config --configure-options) --enable-igbinary CFLAGS="-ggdb3 $CFLAGS"
  make -j4 && make install
)
