#!/bin/bash -xe

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EXTPATH=$1
EXTNAME=$2
EXTRAINFO=$3

cd $EXTPATH

$PHPDIR/phpize

$PHPDIR/php-config || true
./configure --with-php-config=$PHPDIR/php-config --with-$EXTNAME=$EXTRAINFO

make
