#!/usr/bin/env bash

set -xe

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EXTPATH=$1
EXTNAME=$2
EXTRAINFO=$3

cd $EXTPATH

$PHPDIR/phpize

$PHPDIR/php-config || true
export CFLAGS="-ggdb3 $CFLAGS"
./configure --with-php-config=$PHPDIR/php-config --with-$EXTNAME=$EXTRAINFO $($PHPDIR/php-config --configure-options)

make clean all
